// <auto-generated />
using FAQ_App.Models.DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FAQ_App.Migrations
{
    [DbContext(typeof(FAQContext))]
    [Migration("20230704165100_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FAQ_App.Models.DomainModels.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Name = "History"
                        },
                        new
                        {
                            Id = -2,
                            Name = "General"
                        });
                });

            modelBuilder.Entity("FAQ_App.Models.DomainModels.FAQ", b =>
                {
                    b.Property<int>("FAQId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FAQId"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.HasKey("FAQId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TopicId");

                    b.ToTable("FAQs");

                    b.HasData(
                        new
                        {
                            FAQId = -1,
                            Answer = "JavaScript was created by Brendan Eich.",
                            CategoryId = -1,
                            Question = "Who invented JavaScript?",
                            TopicId = -1
                        },
                        new
                        {
                            FAQId = -2,
                            Answer = "Bootstrap is a popular CSS framework that helps you build responsive and mobile-first websites.",
                            CategoryId = -2,
                            Question = "What is Bootstrap?",
                            TopicId = -2
                        },
                        new
                        {
                            FAQId = -3,
                            Answer = "JavaScript is a programming language that allows you to add interactivity and dynamic content to websites.",
                            CategoryId = -2,
                            Question = "What is JavaScript?",
                            TopicId = -1
                        });
                });

            modelBuilder.Entity("FAQ_App.Models.DomainModels.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Name = "JavaScript"
                        },
                        new
                        {
                            Id = -2,
                            Name = "Bootstrap"
                        });
                });

            modelBuilder.Entity("FAQ_App.Models.DomainModels.FAQ", b =>
                {
                    b.HasOne("FAQ_App.Models.DomainModels.Category", "Category")
                        .WithMany("FAQs")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FAQ_App.Models.DomainModels.Topic", "Topic")
                        .WithMany("FAQs")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("FAQ_App.Models.DomainModels.Category", b =>
                {
                    b.Navigation("FAQs");
                });

            modelBuilder.Entity("FAQ_App.Models.DomainModels.Topic", b =>
                {
                    b.Navigation("FAQs");
                });
#pragma warning restore 612, 618
        }
    }
}
